### ISSUE TITLE
Fix top 404s

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-webdev#1112]
Here are the top webdev 404s for the last 30 days. Many of them are for examples; others might be bogus 404s caused by URLs we typed in while working on the docs.

It looks like we've been generating the wrong URL for the hosted copy in the README and http://angular-examples.github.io/. For example, both https://github.com/angular-examples/quickstart and http://angular-examples.github.io link to https://webdev.dartlang.org/examples/ng/doc/quickstart.

@chalin can you please fix generating the /examples/* URLs? I can handle redirects for the other legitimate 404s.

**Top 404s (minus a few that I know have been fixed)**
/examples/ng/doc/quickstart
/examples/ng/doc/toh-6
/examples/ng/doc/toh-5/heroes
/examples/ng/doc/architecture
/examples/ng/doc/toh-1
/examples/ng/doc/toh-4
/examples
/examples/ng/doc/template-syntax
/angular/guide/forms **(this seems bogus)**
/examples/ng/doc/toh-2
/examples/ng/doc/toh-3
/examples/lottery/2-easystart
/examples/ng/doc/forms
/examples/ng/doc/toh-5
/examples/ng/doc/toh-6/dashboard
/examples/toh-6/dashboard
/api/angular_router/angular_router/Route-class **(this works for me; probably dev-time issue)**
/api/angular/angular **(perhaps someone walking up the URL path? consider redirecting to /api/angular/angular/angular-library)**
/examples/acx/lottery/4-final
/examples/ng/doc/router
/examples/ng/doc/server-communication
/api/angular_components/angular_components **(see note for /api/angular/angular)**
/api/angular_components/angular_components/PopupDirective-class **(referrer: google; no class by that name, no mention in angular_components changelog, but [old docs](https://www.dartdocs.org/documentation/angular2_components/0.5.0-beta/angular2_components/PopupDirective-class.html) exist, so it looks like this was removed)**
/api/angular_components/angular_components/PopupDirective/enforceSpaceConstraints
/api/angular_router/angular_router/RouteConfig-class **(this works for me; probably dev-time issue)**
/examples/ng/doc/dependency-injection
/examples/ng/doc/hierarchical-dependency-injection
/examples/ng/doc/lifecycle-hooks
/examples/ng/doc/toh-0
/examples/ng/doc/user-input
/examples/router/abc
/examples/toh-5/detail/11

**Comment by chalin** [comment]
> @chalin can you please fix generating the /examples/* URLs?

Done: https://github.com/dart-lang/dart-doc-syncer/pull/36

**Comment by chalin** [comment]
We shouldn't be getting any 404s for API pages even if individual API page entries disappar. So, I've submitted #1114 which adds a "catch all" rule for API pages.

> I can handle redirects for the other legitimate 404s.

Ok. I'll let you decide if you still want to add specific rewrite rules for, `/api/angular/angular` and `/api/angular_components/angular_components`.

**Comment by chalin** [comment]
Actually, the "catch all" needed to be reverted. I added rules for (via #116):
  - `/api/angular/angular`
  - `/api/angular_components/angular_components`

I believe that this should address the main concerns of this PR

**Comment by chalin** [comment]
Can we close this issue?

**Comment by kwalrath** [comment]
I'm still seeing 404s for /examples/ng/doc/toh-6 (all from cndartlang.com/800.html), so we could fix that, but let's see if they peter out.
