### ISSUE TITLE
[ng] constants for directives not very much mentioned

### ISSUE THREAD

**Issue by Janamou** [dart-lang/site-webdev#857]
Hi,

I have written something about this already here: #856.
The thing is, that lately there was a change, that if I need to use some directives - ngIf, ngModel etc., I need to also include directive constants - FORM_DIRECTIVES, CORE_DIRECTIVES etc...

And this is not very much written (it's kind of important information) like a big warning in the documentation (its only in tutorial). I am talking about these articles:

(List updated by @chalin)

- [x] https://webdev.dartlang.org/angular/guide/displaying-data
- [x] https://webdev.dartlang.org/angular/guide/forms
- [x] https://webdev.dartlang.org/angular/guide/router
- [ ] https://webdev.dartlang.org/angular/guide/template-syntax
- [ ] https://webdev.dartlang.org/angular/guide/structural-directives
- [x] ~https://webdev.dartlang.org/angular/guide/user-input~, #1040

**Comment by kwalrath** [comment]
Thanks for the feedback, Jana. You're right that we need to be explicit about the requirements (imports, constants) for each page.

**Comment by chalin** [comment]
How about an alert like the following (most of the text is borrowed from what we used in the toh-1 page):
<img width="838" alt="screen shot 2017-09-08 at 12 15 41" src="https://user-images.githubusercontent.com/4140793/30221001-a9e19bb2-948f-11e7-86a5-bc363ef7b6c3.png">

This particular alert is for the displaying-data page. I would place it towards the end of the first section that uses a core directive.

**Comment by kwalrath** [comment]
I like it, but I'd tighten up the language and emphasize individual directives a bit more. (We plan to encourage individual directives once the tools make that easier.) Maybe:

> ...annotation. You can list directives individually, or for convenience you can use groups like CORE_DIRECTIVES:

/cc @matanlurey

**Comment by chalin** [comment]
@kwalrath - I've implemented your suggestion.

A few more remarks and questions:
- #1040 cleans out the user-input example, removing angular_forms, since it is not needed.
- The [Template Syntax](https://webdev.dartlang.org/angular/guide/template-syntax) page is a collection of disjoint topics that covering directives from the core and forms. Do we really want to add a general comment at the top that reminds folks to add directions (without being specific about which directives)?
- A similar comment applies to the Structural Directives page.

**Comment by chalin** [comment]
#1041 covers all cases except template-syntax and structural-directives.

**Comment by kwalrath** [comment]
Since template-syntax doesn't even cover imports, leaving out the `directives` text seems reasonable.

I'm less sure about structural-directives, but since it's an "advanced" guide, I'm less concerned about it.

Let's close this and open more specific bugs if people are still having problems.
